config/routes.rb
Radiostats::Application.routes.draw do
  resources :radios

  get "home/index"
  
  get 'about' => 'home#about'
  
  get 'cron/funradio' => 'cron#funradio'
  get 'cron/radiomax' => 'cron#radiomax'
  get 'cron/expres' => 'cron#expres'
  get 'cron/europa2' => 'cron#europa2'
  get 'cron/viva' => 'cron#viva'
  get 'cron/hey' => 'cron#hey'
  get 'cron/antena' => 'cron#antena'
  get 'cron/jemnemelodie' => 'cron#jemnemelodie'
  get 'cron/radio_slovensko' => 'cron#radio_slovensko'
  get 'cron/radio_klasika' => 'cron#radio_klasika'
  get 'cron/radio_regina' => 'cron#radio_regina'
  get 'cron/radio_patria' => 'cron#radio_patria'
  get 'cron/radio_litera' => 'cron#radio_litera'
  get 'cron/radio_devin' => 'cron#radio_devin'
  get 'cron/radio_slovakia_international' => 'cron#radio_slovakia_international'
  get 'cron/radio_junior' => 'cron#radio_junior'
  get 'cron/radio_fm' => 'cron#radio_fm'
  
  get 'song/:id' => 'songs#show', :as => 'song_link', :via => 'get'
  get 'songs' => 'songs#index'
  get 'most_played' => 'songs#most_played'

  resources :interprets do
    get 'page/:page', :action => :index, :on => :collection
  end
  get 'interpret/:id' => 'interprets#show', :as => 'interpret_link', :via => 'get'
  get 'interprets' => 'interprets#index'
  
  get 'search' => 'search#search'
  get 'filter' => 'search#filter'

  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@last_played = Broadcast.order("created_at DESC").includes(:song => [:interpret], :radio => []).limit(10)

	last_week = 7.days.ago..Time.now
	
	@most_played = Broadcast.select("*, COUNT(song_id) AS cnt").where(:created_at => last_week).group("song_id").order("cnt DESC").includes(:song => [:interpret], :radio => []).limit(10)
  end
  
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h2>O RadioStats</h2>

<h3>Čo to je</h3>
<p>Táto aplikácia zhromažduje aktuálne vysielané pesničky v klasických rádiách, v ktorých následne umožňuje vyhľadávať a zobrazovať štatistiku ich hranosti. Projekt vznikol v rámci výskumného seminára na škole.</p>

<h3>Prečo to vzniklo</h3>
<p>Prvotná myšlienka vznikla počas riadenia auta - zapáčila sa mi nejaká pesnička, ale nevedel som jej názov, TrackID alebo Shazam som použiť nemohol (v tom čase som ani nemal mobil s takou funkciou) a cez RDS sa jej názov na Slovensku neprenáša (zákon..). Jediné čo som vedel je názov rádia a približný čas hrania pesničky. To by sa dalo použiť na jej vyhľadanie, ale webové stránky rádií buď nemajú žiadnu históriu playlistu alebo len obmedzenú a nedá sa v nej hľadať. Môj problém rieši táto aplikácia a prináša na jednom mieste štastistiky hranosti pesničiek.</p>

<h3>Má to nedostatky</h3>
<p>O niektorých viem, mám v pláne aj vylepšenia. O prípadných podnetoch mi môžete napísať, ďakujem.</p>

<h3>Kto som</h3>
<p>Som Ondrej Galbavý, študent 2. ročník (máj 2012) na <a href="http://www.fiit.stuba.sk/">FIIT STU</a>. Popri škole vytváram webové stránky. Mimo webov sa okrajovo venujem programovaniu desktopovových aplikácií a elektronike.</p>

<h3>Na čom to beží</h3>
<ul>
<li><a href="http://rubyonrails.org/">Ruby on Rails</a></li>
<li><a href="http://www.mysql.com/">MySQL</a></li>
<li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a></li>
</ul>

<h3>Napíšte mi</h3>
<ul>
<li><a href="mailto:&#111;&#110;&#100;&#114;&#101;&#106;&#46;&#103;&#97;&#108;&#98;&#97;&#118;&#121;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;">&#111;&#110;&#100;&#114;&#101;&#106;&#46;&#103;&#97;&#108;&#98;&#97;&#118;&#121;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;</a></li>
<li><a href="http://twitter.com/OndroNR">@OndroNR</a></li>
</ul>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Posledný 10 pesničiek </h2>
<table class="table table-condensed table-striped">
  <tr>
    <th>Pesnička</th>
	<th>Interpret</th>
	<th>Čas hrania</th>
	<th>Rádio</th>
  </tr>
<% @last_played.each do |br| %>
  <tr>
	<td><%= link_to br.song.name, song_link_path(br.song) %></td>
	<td><%= link_to br.song.interpret.name, interpret_link_path(br.song.interpret) %></td>
	<td><%= br.created_at.strftime("%-d. %-m. %H:%M") %></td>
	<td><%= link_to br.radio.name, radio_path(br.radio) %></td>
  </tr>
<% end %>
</table> 

<h2>Najhranejšie za posledných 7 dní</h2>
<table class="table table-condensed table-striped">
  <tr>
	<th></th>
    <th>Pesnička</th>
	<th>Interpret</th>
	<th>Počet hraní</th>
  </tr>
<% @most_played.each_with_index do |br, i| %>
  <tr>
	<td><%= i+1 %>.</td>
	<td><%= link_to br.song.name, "/song/" + br.song.id.to_s %></td>
	<td><%= link_to br.song.interpret.name, interpret_link_path(br.song.interpret) %></td>
	<td><%= br.cnt %></td>
  </tr>
<% end %>
</table>