config/routes.rb
Radiostats::Application.routes.draw do
  resources :radios

  get "home/index"
  
  get 'about' => 'home#about'
  
  get 'cron/funradio' => 'cron#funradio'
  get 'cron/radiomax' => 'cron#radiomax'
  get 'cron/expres' => 'cron#expres'
  get 'cron/europa2' => 'cron#europa2'
  get 'cron/viva' => 'cron#viva'
  get 'cron/hey' => 'cron#hey'
  get 'cron/antena' => 'cron#antena'
  get 'cron/jemnemelodie' => 'cron#jemnemelodie'
  get 'cron/radio_slovensko' => 'cron#radio_slovensko'
  get 'cron/radio_klasika' => 'cron#radio_klasika'
  get 'cron/radio_regina' => 'cron#radio_regina'
  get 'cron/radio_patria' => 'cron#radio_patria'
  get 'cron/radio_litera' => 'cron#radio_litera'
  get 'cron/radio_devin' => 'cron#radio_devin'
  get 'cron/radio_slovakia_international' => 'cron#radio_slovakia_international'
  get 'cron/radio_junior' => 'cron#radio_junior'
  get 'cron/radio_fm' => 'cron#radio_fm'
  
  get 'song/:id' => 'songs#show', :as => 'song_link', :via => 'get'
  get 'songs' => 'songs#index'
  get 'most_played' => 'songs#most_played'

  resources :interprets do
    get 'page/:page', :action => :index, :on => :collection
  end
  get 'interpret/:id' => 'interprets#show', :as => 'interpret_link', :via => 'get'
  get 'interprets' => 'interprets#index'
  
  get 'search' => 'search#search'
  get 'filter' => 'search#filter'

  

  root :to => 'home#index'

end

app/models/radio.rb
class Radio < ActiveRecord::Base
	has_many :broadcasts
	
	def songs_last(last=20)
		Broadcast.where(:radio_id => self.id).order("created_at DESC").includes(:song => [:interpret]).limit(last)
	end
end

app/controllers/radios_controller.rb
class RadiosController < ApplicationController
  # GET /radios
  # GET /radios.json
  def index
    @radios = Radio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @radios }
    end
  end

  # GET /radios/1
  # GET /radios/1.json
  def show
    @radio = Radio.find(params[:id])
	@songs = @radio.songs_last(10)
	@most_played = Broadcast.week_filter(cookies[:week]).select("song_id, COUNT(song_id) AS cnt").where(:radio_id => params[:id]).group("song_id").order("cnt DESC").includes(:song => [:interpret]).limit(20)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @radio }
    end
  end

  # GET /radios/new
  # GET /radios/new.json
  def new
    @radio = Radio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @radio }
    end
  end

  # GET /radios/1/edit
  def edit
    @radio = Radio.find(params[:id])
  end

  # POST /radios
  # POST /radios.json
  def create
    @radio = Radio.new(params[:radio])

    respond_to do |format|
      if @radio.save
        format.html { redirect_to @radio, notice: 'Radio was successfully created.' }
        format.json { render json: @radio, status: :created, location: @radio }
      else
        format.html { render action: "new" }
        format.json { render json: @radio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /radios/1
  # PUT /radios/1.json
  def update
    @radio = Radio.find(params[:id])

    respond_to do |format|
      if @radio.update_attributes(params[:radio])
        format.html { redirect_to @radio, notice: 'Radio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @radio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /radios/1
  # DELETE /radios/1.json
  def destroy
    @radio = Radio.find(params[:id])
    @radio.destroy

    respond_to do |format|
      format.html { redirect_to radios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/radios_helper.rb
module RadiosHelper
end

app/views/radios/_form.html.erb
<%= form_for(@radio) do |f| %>
  <% if @radio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@radio.errors.count, "error") %> prohibited this radio from being saved:</h2>

      <ul>
      <% @radio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :fancyname %><br />
    <%= f.text_field :fancyname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/radios/edit.html.erb
<h1>Editing radio</h1>

<%= render 'form' %>

<%= link_to 'Show', @radio %> |
<%= link_to 'Back', radios_path %>

app/views/radios/index.html.erb
<h1>Listing radios</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
	<th>Fancyname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @radios.each do |radio| %>
  <tr>
    <td><%= radio.name %></td>
    <td><%= radio.url %></td>
	<td><%= radio.fancyname %></td>
    <td><%= link_to 'Show', Radio.find(radio.id) %></td>
    <td><%= link_to 'Edit', edit_radio_path(Radio.find(radio.id)) %></td>
    <td><%= link_to 'Destroy', Radio.find(radio.id), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Radio', new_radio_path %>

app/views/radios/new.html.erb
<h1>New radio</h1>

<%= render 'form' %>

<%= link_to 'Back', radios_path %>

app/views/radios/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @radio.name %></h1>
<p><%= link_to "web", @radio.url %></p>

<h2>Posledných 10 pesničiek</h2>
<table class="table table-condensed table-striped">
  <tr>
    <th>Názov</th>
	<th>Interpret</th>
	<th>Čas hrania</th>
  </tr>
<% @songs.each do |br| %>
  <tr>
	<td><%= link_to br.song.name, song_link_path(br.song) %></td>
	<td><%= link_to br.song.interpret.name, interpret_link_path(br.song.interpret) %></td>
	<td><%= br.created_at.strftime("%-d. %-m. %H:%M") %></td>
  </tr>
<% end %>
</table>

<h2>Najhranejšie</h2>
<table class="table table-condensed table-striped">
  <tr>
	<th></th>
    <th>Pesnička</th>
	<th>Interpret</th>
	<th>Počet hraní</th>
  </tr>
<% @most_played.each_with_index do |br, i| %>
  <tr>
	<td><%= i+1 %>.</td>
	<td><%= link_to br.song.name, song_link_path(br.song) %></td>
	<td><%= link_to br.song.interpret.name, interpret_link_path(br.song.interpret) %></td>
	<td><%= br.cnt %></td>
  </tr>
<% end %>
</table> 